-   id: remove-query-counts
    name: Remove query count comments
    description: Removes any query count comments, before commiting them to version control.
    entry: remove_query_counts
    language: python
    types: [python]
    stages: [commit]
